### ISSUE TITLE
Add framework target

### ISSUE THREAD

**Issue by Cyberbeni** [TitouanVanBelle/XCTestHTMLReport#149]
It would be cool to also have this tool available as a framework.

**Comment by nacho4d** [comment]
After a long time, this is possible. 

In SPM, XCTestHtmlReport now has two targets:
- XCTestHtmlReport: The usual binary/runnable target
- XCTestHtmlReportCore: Library target, we use this for unit tests. It could be used as a framework too.

I am closing this since I think request has been fulfilled. If I am missing something please reopen or create a new issue.
