### ISSUE TITLE
Provide a way to censor credentials in report if wanted

### ISSUE THREAD

**Issue by leahmeza** [TitouanVanBelle/XCTestHTMLReport#205]
I utilize the slack api to post our html reports generated by our projects to slack channels. However, it is a security concern since the username and password of test accounts are exposed. 

Is there a way/become a way to censor the string credentials, especially in "set up" steps?

**Comment by nacho4d** [comment]
I believe that censoring sensitive information is out of scope of this tool because of these reasons:

- If you have user/passwords in your logs (in xcresults file) that is also a security breach so it should be addressed before logging that information. Please consider using OSLog with new private and public modifiers  https://developer.apple.com/forums/thread/118819

- Same principle applies for screenshots however there is not built in API that *hides* the sensitive info (not at least that I am aware of). This task should be done by the application logic. Framework logic (this tool) has no information about what info is sensitive/non-sensitive.

I would close this issue but if you feel that we should discuss more re-open please.
