### ISSUE TITLE
Failed to extract activity logs

### ISSUE THREAD

**Issue by chrisballinger** [TitouanVanBelle/XCTestHTMLReport#56]
> Warning: Failed to extract activity logs. Could not locate match for "Running tests..."'

When using the output from `fastlane scan` there is a warning printed.

[BonMot-OSX.test_result.zip](https://github.com/TitouanVanBelle/XCTestHTMLReport/files/1933834/BonMot-OSX.test_result.zip)

**Comment by TitouanVanBelle** [comment]
Thanks for the report. What version of Xcode are you using?

**Comment by chrisballinger** [comment]
9.3

**Comment by ripunjayasaran** [comment]
@TitouanVanBelle : I have seen this issue happening on XCode 9.2 as well.

**Comment by chrisballinger** [comment]
The report HTML seems to look fine, so maybe it's just a false alarm? Great job btw!

**Comment by TitouanVanBelle** [comment]
@chrisballinger Not sure how that relates to this specific issue. This issue was caused because a string ("Running tests...") that the tool was looking for before doesn't seem to be there anymore. I already created a PR for the fix but still need to test it on different version of Xcode to make sure that it still works.
